name: mediuitleg
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  http: ^1.2.2
  camera: ^0.11.0+2
  flutter_tesseract_ocr: ^0.4.28
  image: ^4.0.15
  flutter_tts: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tessdata/eng.traineddata
    - assets/tessdata/nld.traineddata
    - assets/tessdata/tessdata_config.json
